### ISSUE TITLE
Parameters to graphql keyword

### ISSUE THREAD

**Issue by schroeer** [graphql-perl/Dancer2-Plugin-GraphQL#2]
Assuming the same database and schema as provided [here](https://github.com/graphql-perl/GraphQL-Plugin-Convert-DBIC/issues/15#issue-528789007).

```
use strict;
use warnings;
use Dancer2;
use Dancer2::Plugin::GraphQL;
use GraphQL::Plugin::Convert::DBIC;
use Schema;

set charset  => 'UTF-8';
set template => 'simple';
set plugins  => { 'GraphQL' => { graphiql => 1 } };

my $converted = GraphQL::Plugin::Convert::DBIC->to_graphql(Schema->connect('dbi:SQLite:dogowner.sqlite', '', ''));

graphql '/graphql' => sub {
    my ($app, $body, $execute) = @_;
    $execute->(
        $converted->{schema},
        $body->{query},
        $converted->{root_value},
        $app->request->headers,
        $body->{variables},
        $body->{operationName},
        $converted->{resolver},
    );
};

graphql '/graphql2' => ['DBIC', Schema->connect('dbi:SQLite:dogowner.sqlite', '', '')];

dance();
```

`/graphql` works as expected. The way I read the documentation, `/graphql2` should work too. However, I get the following error:

`Can't call method \"name\" on an undefined value at C:/perl/perl/site/lib/GraphQL/Plugin/Convert/DBIC.pm line 221.`

I find this part of the documentation very difficult to read. The relevant code in `DBIC.pm` does not help much.

**Comment by mohawk2** [comment]
Thanks for this exceptionally good report, which made it straightforward to repro this!

What was happening was when a `::Convert` supplied a resolver, we used that as a handler, and tried to use the default resolver. Neither was correct. Now it will supply a handler if none is provided, and it should work.

Released as 0.08.
